.TH "C:/Users/User/Desktop/rt_assignment_1 Directory Reference" 3 "Wed Jan 6 2021" "Version 0.1.0" "Research Track 1: Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/User/Desktop/rt_assignment_1 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBscripts\fP"
.br
.in -1c
