.TH "C:/Users/User/Desktop/rt_assignment_1/scripts Directory Reference" 3 "Wed Jan 6 2021" "Version 0.1.0" "Research Track 1: Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/User/Desktop/rt_assignment_1/scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBremote_server\&.py\fP"
.br
.ti -1c
.RI "file \fBrobot_controller\&.py\fP"
.br
.in -1c
