.TH "C:/Users/User/Desktop/rt_assignment_1/scripts/remote_server.py" 3 "Wed Jan 6 2021" "Version 0.1.0" "Research Track 1: Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/User/Desktop/rt_assignment_1/scripts/remote_server.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBremote_server\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBremote_server\&.handle_random_target\fP (req)"
.br
.ti -1c
.RI "def \fBremote_server\&.random_target_gen\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Track 1: Assignment 1 from the source code\&.
