.TH "robot_controller" 3 "Wed Jan 6 2021" "Version 0.1.0" "Research Track 1: Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robot_controller
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBthe_distance_to_target\fP (target)"
.br
.ti -1c
.RI "def \fBcall_to_service\fP ()"
.br
.ti -1c
.RI "def \fBpose_clbk\fP (pose_message)"
.br
.ti -1c
.RI "def \fBcontrol\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBcurrent_position_x\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBcurrent_position_y\fP = 0\&.0"
.br
.ti -1c
.RI "float \fByaw\fP = 0\&.0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def robot_controller\&.call_to_service ()"

.PP
.nf
Sends a service request to random_target with a status
message

Returns:
    (Object): A target object containing the x and y
    coordinates

.fi
.PP
 
.PP
Definition at line 40 of file robot_controller\&.py\&.
.SS "def robot_controller\&.control ()"

.PP
.nf
The control function sends a request to random_target service,
accepts a response of the cordinates of the new target position
and sets the robot to navigate to the target coordinates

.fi
.PP
 
.PP
Definition at line 88 of file robot_controller\&.py\&.
.SS "def robot_controller\&.pose_clbk ( pose_message)"

.PP
.nf
The pose callback function takes the position and posture of
the robot from the argument "pose_message" and set it to
three global variables containing the x, y and yaw position.

Args:
    pose_message (Object): an object containing all the values
    of the current position and posture of the robot

.fi
.PP
 
.PP
Definition at line 61 of file robot_controller\&.py\&.
.SS "def robot_controller\&.the_distance_to_target ( target)"

.PP
.nf
Calculates the distance between the robot and the
target

Args:
    target (Object): Object containing the x and y
    coodinates of the new target

Returns:
    (int): returns a tuple of the value of the
    distance to the target and the required yaw to
    face the direction of the target

.fi
.PP
 
.PP
Definition at line 18 of file robot_controller\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "float robot_controller\&.current_position_x = 0\&.0"

.PP
Definition at line 13 of file robot_controller\&.py\&.
.SS "float robot_controller\&.current_position_y = 0\&.0"

.PP
Definition at line 14 of file robot_controller\&.py\&.
.SS "float robot_controller\&.yaw = 0\&.0"

.PP
Definition at line 15 of file robot_controller\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Track 1: Assignment 1 from the source code\&.
