.TH "C:/Users/User/Desktop/rt_assignment_1/scripts/robot_controller.py" 3 "Wed Jan 6 2021" "Version 0.1.0" "Research Track 1: Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/User/Desktop/rt_assignment_1/scripts/robot_controller.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrobot_controller\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrobot_controller\&.the_distance_to_target\fP (target)"
.br
.ti -1c
.RI "def \fBrobot_controller\&.call_to_service\fP ()"
.br
.ti -1c
.RI "def \fBrobot_controller\&.pose_clbk\fP (pose_message)"
.br
.ti -1c
.RI "def \fBrobot_controller\&.control\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBrobot_controller\&.current_position_x\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBrobot_controller\&.current_position_y\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBrobot_controller\&.yaw\fP = 0\&.0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Track 1: Assignment 1 from the source code\&.
